POST localhost:8001/auth/sign-in/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
POST localhost:8001/api/posts/1/vote/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzE3MjM4LCJpYXQiOjE3NDczMTY5MzgsImp0aSI6IjU1NDJlYzhhMmE4ZTQyMmViMTRmMzJlZTk4NDcxZTcxIiwidXNlcl9pZCI6MX0.2cLzB_DMZcPjsxiNvencO4HfrM9OAkbh5lf37MyEbBw

{
  "type": "like"
}

###
POST localhost:8001/api/posts/1/vote/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzE3MjM4LCJpYXQiOjE3NDczMTY5MzgsImp0aSI6IjU1NDJlYzhhMmE4ZTQyMmViMTRmMzJlZTk4NDcxZTcxIiwidXNlcl9pZCI6MX0.2cLzB_DMZcPjsxiNvencO4HfrM9OAkbh5lf37MyEbBw

{
  "type": "dislike"
}

####
#POST localhost:8001/api/posts/1/vote/ HTTP/1.1
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzE3MjM4LCJpYXQiOjE3NDczMTY5MzgsImp0aSI6IjU1NDJlYzhhMmE4ZTQyMmViMTRmMzJlZTk4NDcxZTcxIiwidXNlcl9pZCI6MX0.2cLzB_DMZcPjsxiNvencO4HfrM9OAkbh5lf37MyEbBw
#
#{
#  "type": "dislike"
#}